// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbDJC3RLWeAHf0xaj8AFeO4jfzmLOFAkA',
    appId: '1:715951842286:web:96215e7463d08b241964ff',
    messagingSenderId: '715951842286',
    projectId: 'shootinsights',
    authDomain: 'shootinsights.firebaseapp.com',
    storageBucket: 'shootinsights.firebasestorage.app',
    measurementId: 'G-T2F55YJ0R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5eEaIePi4t6rFdi8KvVWF0hUwU8m8No',
    appId: '1:715951842286:android:73b0cee3f2ca08f61964ff',
    messagingSenderId: '715951842286',
    projectId: 'shootinsights',
    storageBucket: 'shootinsights.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFEc3Y21EkWCikqm6w2sBW4NpV8Tmh2i0',
    appId: '1:715951842286:ios:b0436ff67916ed331964ff',
    messagingSenderId: '715951842286',
    projectId: 'shootinsights',
    storageBucket: 'shootinsights.firebasestorage.app',
    iosBundleId: 'com.example.bulletseed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFEc3Y21EkWCikqm6w2sBW4NpV8Tmh2i0',
    appId: '1:715951842286:ios:b0436ff67916ed331964ff',
    messagingSenderId: '715951842286',
    projectId: 'shootinsights',
    storageBucket: 'shootinsights.firebasestorage.app',
    iosBundleId: 'com.example.bulletseed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbDJC3RLWeAHf0xaj8AFeO4jfzmLOFAkA',
    appId: '1:715951842286:web:04d5968e4ba0dc9a1964ff',
    messagingSenderId: '715951842286',
    projectId: 'shootinsights',
    authDomain: 'shootinsights.firebaseapp.com',
    storageBucket: 'shootinsights.firebasestorage.app',
    measurementId: 'G-D8J17TVTQM',
  );
}
